package vista.forms;

import modelo.dao.HabitacionDAO;
import modelo.dto.HabitacionDTO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;

public class HabitacionesForm extends javax.swing.JFrame {
    
    private RegistroClienteForm ventanaPrincipal; 
    private HabitacionDTO habitacionSeleccionada;


    public HabitacionesForm(RegistroClienteForm ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        this.setTitle("Seleccionar Habitación");
        this.setLocationRelativeTo(ventanaPrincipal);

        // Llamamos al método que configura y actualiza nuestros botones
        configurarYActualizarBotones();
    }
    
    private HabitacionesForm() {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
    }
    
    private void configurarYActualizarBotones() {
    try {
        HabitacionDAO dao = new HabitacionDAO();
        ArrayList<HabitacionDTO> habitaciones = (ArrayList<HabitacionDTO>) dao.listarTodas();

        for (HabitacionDTO habitacion : habitaciones) {
            JButton botonCorrespondiente = null;

            switch (habitacion.getNumero()) {
                case 101: botonCorrespondiente = HbtSimple01; break;
                case 102: botonCorrespondiente = HbtSimple02; break;
                case 103: botonCorrespondiente = HbtSimple03; break;
                case 201: botonCorrespondiente = HbtDoble01; break;
                case 202: botonCorrespondiente = HbtDoble02; break;
                case 203: botonCorrespondiente = HbtDoble03; break;
                case 301: botonCorrespondiente = HbtTriple01; break;
                case 302: botonCorrespondiente = HbtTriple02; break;
            }

            if (botonCorrespondiente != null) {
                if (!habitacion.isOcupada()) {
                    botonCorrespondiente.setBackground(new Color(0, 153, 0));
                    botonCorrespondiente.setEnabled(true);

                    // Quita listeners anteriores
                    for (ActionListener al : botonCorrespondiente.getActionListeners()) {
                        botonCorrespondiente.removeActionListener(al);
                    }

                    // NUEVA LÓGICA: solo seleccionar, no cerrar ventana
                    HabitacionDTO h = habitacion; // para usar en lambda
                    botonCorrespondiente.addActionListener(e -> {
                        // guardamos la habitación seleccionada en esta ventana
                        habitacionSeleccionada = h;
                        // feedback visual (opcional)
                        JOptionPane.showMessageDialog(this,
                            "Has seleccionado la habitación " + h.getNumero() + " (" + h.getTipo() + ")");
                    });
                } else {
                    botonCorrespondiente.setBackground(Color.RED);
                    botonCorrespondiente.setEnabled(false);
                }

                botonCorrespondiente.setText("Hab. " + habitacion.getNumero() + " (" + habitacion.getTipo() + ")");
                botonCorrespondiente.setForeground(Color.WHITE);
                botonCorrespondiente.setOpaque(true);
                botonCorrespondiente.setBorderPainted(false);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar habitaciones: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        HbtSimple01 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        HbtSimple02 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        HbtDoble01 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        HbtDoble02 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        HbtTriple01 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        HbtSimple03 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        HbtDoble03 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        HbtTriple02 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnAceptar.setText("ACEPTAR");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 130, 40));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Habitaciones Disponibles");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 290, 20));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HbtSimple01.setBackground(new java.awt.Color(0, 102, 0));
        HbtSimple01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HbtSimple01.setText("Habitacion Simple - 101");
        HbtSimple01.setBorder(null);
        HbtSimple01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtSimple01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtSimple01, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HbtSimple01, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 70));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HbtSimple02.setBackground(new java.awt.Color(0, 102, 0));
        HbtSimple02.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HbtSimple02.setText("Habitacion Simple - 102");
        HbtSimple02.setBorder(null);
        HbtSimple02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtSimple02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtSimple02, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HbtSimple02, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 180, 70));

        jPanel5.setBackground(new java.awt.Color(204, 102, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HbtDoble01.setBackground(new java.awt.Color(204, 102, 0));
        HbtDoble01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HbtDoble01.setText("Habitacion Doble - 201");
        HbtDoble01.setBorder(null);
        HbtDoble01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtDoble01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtDoble01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtDoble01, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 70));

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HbtDoble02.setBackground(new java.awt.Color(204, 102, 0));
        HbtDoble02.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HbtDoble02.setText("Habitacion Doble - 202");
        HbtDoble02.setBorder(null);
        HbtDoble02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtDoble02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtDoble02, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HbtDoble02, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 180, 70));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HbtTriple01.setBackground(new java.awt.Color(0, 153, 153));
        HbtTriple01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HbtTriple01.setText("Habitacion Triple - 301");
        HbtTriple01.setBorder(null);
        HbtTriple01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtTriple01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(HbtTriple01, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(HbtTriple01, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 180, 70));

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HbtSimple03.setBackground(new java.awt.Color(0, 102, 0));
        HbtSimple03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HbtSimple03.setText("Habitacion Simple -103");
        HbtSimple03.setBorder(null);
        HbtSimple03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtSimple03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtSimple03, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtSimple03, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 190, -1));

        jPanel7.setBackground(new java.awt.Color(255, 102, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HbtDoble03.setBackground(new java.awt.Color(204, 102, 0));
        HbtDoble03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HbtDoble03.setText("Habitacion Doble - 203");
        HbtDoble03.setBorder(null);
        HbtDoble03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtDoble03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtDoble03, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtDoble03, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HbtTriple02.setBackground(new java.awt.Color(0, 153, 153));
        HbtTriple02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HbtTriple02.setText("Habitacion Triple - 302");
        HbtTriple02.setBorder(null);
        HbtTriple02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtTriple02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtTriple02, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HbtTriple02, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HbtSimple01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtSimple01ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> new RegistroClienteForm().setVisible(true));
    }//GEN-LAST:event_HbtSimple01ActionPerformed

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
        if (habitacionSeleccionada == null) {
        JOptionPane.showMessageDialog(this,
            "Primero seleccione una habitación haciendo clic en uno de los botones.");
        return;
    }
    if (ventanaPrincipal != null) {
        ventanaPrincipal.setHabitacionSeleccionada(habitacionSeleccionada);
        ventanaPrincipal.setVisible(true);
    }

    this.dispose();
        
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void HbtDoble02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtDoble02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HbtDoble02ActionPerformed

    private void HbtTriple02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtTriple02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HbtTriple02ActionPerformed

    private void HbtDoble03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtDoble03ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_HbtDoble03ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (ventanaPrincipal != null) {
        ventanaPrincipal.setVisible(true);
    }
         this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HbtSimple02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtSimple02ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HbtSimple02ActionPerformed

    private void HbtSimple03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtSimple03ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HbtSimple03ActionPerformed

    private void HbtDoble01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtDoble01ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HbtDoble01ActionPerformed

    private void HbtTriple01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtTriple01ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HbtTriple01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            //logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HabitacionesForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton HbtDoble01;
    private javax.swing.JButton HbtDoble02;
    private javax.swing.JButton HbtDoble03;
    private javax.swing.JButton HbtSimple01;
    private javax.swing.JButton HbtSimple02;
    private javax.swing.JButton HbtSimple03;
    private javax.swing.JButton HbtTriple01;
    private javax.swing.JButton HbtTriple02;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
        private void actualizarAspectoBoton(JButton boton, HabitacionDTO h) {
        String nombreBase = "Habitacion-" + h.getNumero(); 
        String estadoTexto = h.getEstadoTexto(); 

        // NOTA: El diseñador ha puesto los botones dentro de JPanels de color.

//        if (h.estaOcupada()) {
//            boton.setBackground(Color.RED);
//            boton.setForeground(Color.WHITE);
//        } else {
//            boton.setBackground(Color.GREEN);
//            boton.setForeground(Color.BLACK);
//        }

        // Mantiene el nombre base y añade el estado actualizado
        boton.setText(nombreBase + " (" + estadoTexto + ")");

        // Estas líneas son cruciales cuando usas diseñadores
        boton.setOpaque(true); 
        boton.setBorderPainted(false);
    }
}
