package vista.forms;

import javax.swing.JOptionPane;
import modelo.dto.UsuarioDTO;
import modelo.logica.Login;

public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    public LoginForm() {
        
        this.getRootPane().setDefaultButton(BotonLogin);
        initComponents();
        this.setTitle("iniciar Sesion - Admin or User");
        this.setLocationRelativeTo(null);
    }
     public  void goLogin(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextoTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextoContraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JTextField();
        SeparadorUsuario = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        BotonLogin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BotonExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(215, 225, 234));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        TextoTitulo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        TextoTitulo.setForeground(new java.awt.Color(51, 51, 51));
        TextoTitulo.setText("Welcome!");
        jPanel1.add(TextoTitulo);
        TextoTitulo.setBounds(120, 50, 80, 28);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 180, 90, 18);

        TextoContraseña.setBorder(null);
        jPanel1.add(TextoContraseña);
        TextoContraseña.setBounds(30, 200, 250, 20);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Username ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 90, 18);

        TextoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextoUsuario.setBorder(null);
        TextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(TextoUsuario);
        TextoUsuario.setBounds(30, 120, 250, 24);

        SeparadorUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(SeparadorUsuario);
        SeparadorUsuario.setBounds(30, 150, 247, 10);

        jPanel2.setBackground(new java.awt.Color(215, 225, 234));

        BotonLogin.setBackground(new java.awt.Color(215, 225, 234));
        BotonLogin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonLogin.setText("Login");
        BotonLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(170, 270, 110, 40);

        jPanel3.setBackground(new java.awt.Color(215, 225, 234));

        BotonExit.setBackground(new java.awt.Color(215, 225, 234));
        BotonExit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonExit.setText("Exit");
        BotonExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 270, 100, 40);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel2.setText("Hoteles Eclipse");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 20, 170, 28);

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 223, 250, 10);

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 310, 350));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        jLabel8.setText("@Software beta");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoUsuarioActionPerformed

    private void BotonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotonExitActionPerformed

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed
        String user = TextoUsuario.getText();
        String pass = new String(TextoContraseña.getPassword());
        
        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese usuario y contraseña", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (login.validarCredenciales()) {
            UsuarioDTO usuario = login.getUsuarioLogueado();
            JOptionPane.showMessageDialog(this, "Bienvenido, " + usuario.getNombrePersona() + " (" + usuario.getNombreRol() + ")");

            RegistroClienteForm form = new RegistroClienteForm();
            form.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//         java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true)); 
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonExit;
    private javax.swing.JButton BotonLogin;
    private javax.swing.JSeparator SeparadorUsuario;
    private javax.swing.JPasswordField TextoContraseña;
    private javax.swing.JLabel TextoTitulo;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
