/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.forms;

/**
 *
 * @author drola
 */
import java.util.ArrayList;
import java.util.List;
import modelo.dto.BoletaDTO;
import modelo.dto.ReservaDTO;
import modelo.dto.ClienteDTO;
import modelo.logica.GestorHotel;
import modelo.dto.HabitacionDTO;
import javax.swing.JOptionPane;
import modelo.entidades.ServicioAdicional;
import modelo.entidades.ServicioAguaCaliente;
import modelo.entidades.ServicioEstacionamiento;
import modelo.entidades.ServicioSauna;
import modelo.logica.GenerarBoleta;

public class RegistroClienteForm extends javax.swing.JFrame {
    
    private GestorHotel gestor;
    private ClienteDTO clienteActual;
    private ReservaDTO reservaActual;
    private HabitacionDTO habitacionSeleccionada;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroClienteForm.class.getName());

    /**
     * Creates new form RegistroClienteForm
     */
 
    public RegistroClienteForm() {
        initComponents();
        this.setTitle("Menu Principal");
        this.gestor = new GestorHotel();
        lblHabitacionInfo.setText("Ninguna habitación seleccionada");
        this.setLocationRelativeTo(null);
        

    }
    
    
    
    public RegistroClienteForm(GestorHotel gestor) {
        initComponents();
          this.setTitle("Menu Principal");
        this.gestor = gestor;
        lblHabitacionInfo.setText("Ninguna habitación seleccionada");
        this.setLocationRelativeTo(null);
        // escuchar al momento de cerrar la ventana
//        this.addWindowListener(new java.awt.event.WindowAdapter() {
//    @Override
//    public void windowClosed(java.awt.event.WindowEvent windowEvent) {
//        // Al cerrarse la Ventana A, se ejecuta esta lógica:
//        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true)); 
//    }
//});
    }
    
    public void setHabitacionSeleccionada(HabitacionDTO habitacion) {
        this.habitacionSeleccionada = habitacion;
        if (habitacion != null) {
            lblHabitacionInfo.setText("Seleccionada: Hab. " + habitacion.getNumero() + " (" + habitacion.getTipo() + ")");
        } else {
            lblHabitacionInfo.setText("Ninguna habitación seleccionada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonBoletas = new javax.swing.JButton();
        BotonReservas = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        btnStock1 = new javax.swing.JButton();
        btnStock2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnStock3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresoDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ingresoTelefono = new javax.swing.JTextField();
        BotonRegistro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ingresoName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        BotonSauna = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        BotonAguaCaliente = new javax.swing.JRadioButton();
        BotonEstacionamiento = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        estancia = new javax.swing.JTextField();
        BtnHabitaciones = new javax.swing.JButton();
        lblHabitacionInfo = new javax.swing.JLabel();
        BtnHabitaciones1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        wp.setBackground(new java.awt.Color(249, 250, 255));
        wp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(174, 190, 213));

        jPanel2.setBackground(new java.awt.Color(202, 218, 241));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        BotonBoletas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonBoletas.setForeground(new java.awt.Color(51, 51, 51));
        BotonBoletas.setText("Ticket");
        BotonBoletas.setBorder(null);
        BotonBoletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBoletasActionPerformed(evt);
            }
        });

        BotonReservas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonReservas.setForeground(new java.awt.Color(51, 51, 51));
        BotonReservas.setText("Booking");
        BotonReservas.setBorder(null);
        BotonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReservasActionPerformed(evt);
            }
        });

        btnStock.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnStock.setForeground(new java.awt.Color(51, 51, 51));
        btnStock.setText("Stock");
        btnStock.setBorder(null);
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        btnStock1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnStock1.setForeground(new java.awt.Color(51, 51, 51));
        btnStock1.setText("Operarios");
        btnStock1.setBorder(null);
        btnStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStock1ActionPerformed(evt);
            }
        });

        btnStock2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnStock2.setForeground(new java.awt.Color(51, 51, 51));
        btnStock2.setText("Finanzas");
        btnStock2.setBorder(null);
        btnStock2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStock2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("@Software beta");

        btnStock3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnStock3.setForeground(new java.awt.Color(51, 51, 51));
        btnStock3.setText("agregar otra idea de form");
        btnStock3.setBorder(null);
        btnStock3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStock3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(574, 574, 574))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonBoletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStock1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStock2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStock3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnStock3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStock2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        wp.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 520));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Registrar  Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        wp.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 220, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DNI");

        ingresoDNI.setBorder(null);
        ingresoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDNIActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Celular");

        ingresoTelefono.setBorder(null);
        ingresoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoTelefonoActionPerformed(evt);
            }
        });

        BotonRegistro.setBackground(new java.awt.Color(174, 190, 213));
        BotonRegistro.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BotonRegistro.setForeground(new java.awt.Color(51, 51, 51));
        BotonRegistro.setText("Register");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Extra");

        ingresoName.setBorder(null);
        ingresoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNameActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("TIpo de Habitacion");

        BotonSauna.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotonSauna.setText("  Sauna");
        BotonSauna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSaunaActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nombre");

        BotonAguaCaliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotonAguaCaliente.setText("Agua Caliente");
        BotonAguaCaliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAguaCalienteActionPerformed(evt);
            }
        });

        BotonEstacionamiento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotonEstacionamiento.setText("Estacionamiento");
        BotonEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstacionamientoActionPerformed(evt);
            }
        });

        jLabel4.setText("Dias de Estancia:");

        estancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estanciaActionPerformed(evt);
            }
        });

        BtnHabitaciones.setText("Habitaciones");
        BtnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHabitacionesActionPerformed(evt);
            }
        });

        lblHabitacionInfo.setText("Habitacion elejida");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(121, 121, 121))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingresoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(ingresoName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(BotonAguaCaliente)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ingresoDNI)
                                    .addComponent(jSeparator1)
                                    .addComponent(BtnHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(BotonEstacionamiento)))
                                        .addGap(0, 38, Short.MAX_VALUE)))
                                .addGap(41, 41, 41))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblHabitacionInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(estancia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonSauna, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresoName, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(ingresoDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHabitaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHabitacionInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSauna)
                    .addComponent(BotonAguaCaliente)
                    .addComponent(BotonEstacionamiento))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(estancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        wp.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 470, 360));

        BtnHabitaciones1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        BtnHabitaciones1.setText("Cerrar sesion");
        BtnHabitaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHabitaciones1ActionPerformed(evt);
            }
        });
        wp.add(BtnHabitaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Operador : David Rolando");
        wp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBoletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBoletasActionPerformed
        if (this.reservaActual != null && this.clienteActual != null) {
            // Generamos la factura y la guardamos en la base de datos
            BoletaDTO facturaGuardada = gestor.generarFactura(this.reservaActual);
            GenerarBoleta.generarFactura(facturaGuardada);
            if (facturaGuardada != null) {
                JOptionPane.showMessageDialog(this, "Factura generada y guardada en la base de datos con ID: " + facturaGuardada.getFacturaID(), "Factura Generada", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al generar y guardar la factura en la base de datos.", "Error de Facturación", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe completar una reserva antes de generar una boleta.", "Acción Requerida", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BotonBoletasActionPerformed

    private void BotonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReservasActionPerformed

        BookingForm ventanaTabla = new BookingForm(this.gestor);

        ventanaTabla.setVisible(true);

    }//GEN-LAST:event_BotonReservasActionPerformed

    private void ingresoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoDNIActionPerformed

    }//GEN-LAST:event_ingresoDNIActionPerformed

    private void ingresoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoTelefonoActionPerformed

    }//GEN-LAST:event_ingresoTelefonoActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        String nombre = ingresoName.getText();
        String dni = ingresoDNI.getText();
        String telefono = ingresoTelefono.getText();
        String diasEstanciaStr = estancia.getText();
        int diasDeEstancia;

        // validacion; ingreso de datos
        if (nombre.isEmpty() || dni.isEmpty() || telefono.isEmpty() || diasEstanciaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos de datos personales son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (this.habitacionSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una habitación antes de registrar.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            diasDeEstancia = Integer.parseInt(diasEstanciaStr);
            if (diasDeEstancia <= 0) {
                JOptionPane.showMessageDialog(this, "El número de días debe ser un entero positivo.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para los días de estancia.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //iniciar nuevo cliente con argumentos ingresados por usuario
        this.clienteActual = gestor.registrarNuevoCliente(nombre, dni, telefono);

        //add servicios
        List<ServicioAdicional> serviciosSeleccionados = new ArrayList<>();
        if (BotonSauna.isSelected()) {
            serviciosSeleccionados.add(new ServicioSauna());
        }

        if (BotonEstacionamiento.isSelected()) {
            serviciosSeleccionados.add(new ServicioEstacionamiento());
        }

        if (BotonAguaCaliente.isSelected()) {
            serviciosSeleccionados.add(new ServicioAguaCaliente());
        }

        // Creamos la reserva con servicios
        this.reservaActual = gestor.crearReserva(
            clienteActual,
            this.habitacionSeleccionada,
            diasDeEstancia,
            serviciosSeleccionados
        );

        if (reservaActual != null) {
            JOptionPane.showMessageDialog(this, "Reserva creada con éxito para " + clienteActual.getNombre());
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear la reserva. La habitación ya no está disponible.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void ingresoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNameActionPerformed

    }//GEN-LAST:event_ingresoNameActionPerformed

    private void BotonSaunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSaunaActionPerformed

    }//GEN-LAST:event_BotonSaunaActionPerformed

    private void BotonAguaCalienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAguaCalienteActionPerformed

    }//GEN-LAST:event_BotonAguaCalienteActionPerformed

    private void BotonEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstacionamientoActionPerformed

    }//GEN-LAST:event_BotonEstacionamientoActionPerformed

    private void estanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estanciaActionPerformed

    }//GEN-LAST:event_estanciaActionPerformed

    private void BtnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHabitacionesActionPerformed
        HabitacionesForm ventanaHabitaciones = new HabitacionesForm(this.gestor, this);
        ventanaHabitaciones.setVisible(true);
    }//GEN-LAST:event_BtnHabitacionesActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        StockForm ventanaStock = new StockForm();
        ventanaStock.setLocationRelativeTo(null);
        ventanaStock.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStock1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStock1ActionPerformed

    private void btnStock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStock2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStock2ActionPerformed

    private void BtnHabitaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHabitaciones1ActionPerformed
        LoginForm ventana = new LoginForm();
        this.dispose();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_BtnHabitaciones1ActionPerformed

    private void btnStock3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStock3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStock3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroClienteForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonAguaCaliente;
    private javax.swing.JButton BotonBoletas;
    private javax.swing.JRadioButton BotonEstacionamiento;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JButton BotonReservas;
    private javax.swing.JRadioButton BotonSauna;
    private javax.swing.JButton BtnHabitaciones;
    private javax.swing.JButton BtnHabitaciones1;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnStock1;
    private javax.swing.JButton btnStock2;
    private javax.swing.JButton btnStock3;
    private javax.swing.JTextField estancia;
    private javax.swing.JTextField ingresoDNI;
    private javax.swing.JTextField ingresoName;
    private javax.swing.JTextField ingresoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblHabitacionInfo;
    private javax.swing.JPanel wp;
    // End of variables declaration//GEN-END:variables
}
