package vista.forms;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

import modelo.dto.*;
import modelo.dao.*;
import modelo.entidades.ServicioAdicional;
import modelo.entidades.ServicioAguaCaliente;
import modelo.entidades.ServicioEstacionamiento;
import modelo.entidades.ServicioSauna;
import modelo.logica.GenerarBoleta;
import modelo.servicio.BoletaService;
import modelo.servicio.ReservaService;

public class RegistroClienteForm extends javax.swing.JFrame {
    
    private ClienteDTO clienteActual;
    private ReservaDTO reservaActual;
    private HabitacionDTO habitacionSeleccionada;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroClienteForm.class.getName());

    public RegistroClienteForm() {
        initComponents();
        this.setTitle("Menu Principal");
        lblHabitacionInfo.setText("Ninguna habitación seleccionada");
        this.setLocationRelativeTo(null);
    }
    
    
    public void setHabitacionSeleccionada(HabitacionDTO habitacion) {
        this.habitacionSeleccionada = habitacion;
        if (habitacion != null) {
            lblHabitacionInfo.setText("Seleccionada: Hab. " + habitacion.getNumero() + " (" + habitacion.getTipo() + ")");
        } else {
            lblHabitacionInfo.setText("Ninguna habitación seleccionada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonBoletas = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        btnOperarios = new javax.swing.JButton();
        btnFinanzas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnLimpieza = new javax.swing.JButton();
        btnOperarios1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ingresoDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ingresoTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ingresoName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BotonSauna = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        BotonAguaCaliente = new javax.swing.JRadioButton();
        BotonEstacionamiento = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        estancia = new javax.swing.JTextField();
        BtnHabitaciones = new javax.swing.JButton();
        lblHabitacionInfo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        BotonRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnHabitaciones1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        wp.setBackground(new java.awt.Color(249, 250, 255));
        wp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(174, 190, 213));

        jPanel2.setBackground(new java.awt.Color(202, 218, 241));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        BotonBoletas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonBoletas.setForeground(new java.awt.Color(51, 51, 51));
        BotonBoletas.setText("Ticket");
        BotonBoletas.setBorder(null);
        BotonBoletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBoletasActionPerformed(evt);
            }
        });

        btnBooking.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(51, 51, 51));
        btnBooking.setText("Booking");
        btnBooking.setBorder(null);
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        btnStock.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnStock.setForeground(new java.awt.Color(51, 51, 51));
        btnStock.setText("Activos");
        btnStock.setBorder(null);
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        btnOperarios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnOperarios.setForeground(new java.awt.Color(51, 51, 51));
        btnOperarios.setText("Operarios");
        btnOperarios.setBorder(null);
        btnOperarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperariosActionPerformed(evt);
            }
        });

        btnFinanzas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnFinanzas.setForeground(new java.awt.Color(51, 51, 51));
        btnFinanzas.setText("Finanzas");
        btnFinanzas.setBorder(null);
        btnFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanzasActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        jLabel8.setText("@Software beta");

        btnLimpieza.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnLimpieza.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpieza.setText("Limpieza");
        btnLimpieza.setBorder(null);
        btnLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiezaActionPerformed(evt);
            }
        });

        btnOperarios1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnOperarios1.setForeground(new java.awt.Color(51, 51, 51));
        btnOperarios1.setText("Graficos");
        btnOperarios1.setBorder(null);
        btnOperarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperarios1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(391, 391, 391))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOperarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOperarios, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(105, 105, 105)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(btnOperarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOperarios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        wp.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Registrar  Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        wp.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 220, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        ingresoDNI.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ingresoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDNIActionPerformed(evt);
            }
        });

        jLabel2.setText("Celular :");

        ingresoTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ingresoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoTelefonoActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Extra");

        ingresoName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ingresoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de Habitacion");

        BotonSauna.setText("  Sauna");
        BotonSauna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSaunaActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre :");

        BotonAguaCaliente.setText("Agua Caliente");
        BotonAguaCaliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAguaCalienteActionPerformed(evt);
            }
        });

        BotonEstacionamiento.setText("Estacionamiento");
        BotonEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstacionamientoActionPerformed(evt);
            }
        });

        jLabel4.setText("Dias de Estancia:");

        estancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estanciaActionPerformed(evt);
            }
        });

        BtnHabitaciones.setText("Habitaciones");
        BtnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHabitacionesActionPerformed(evt);
            }
        });

        lblHabitacionInfo.setText("Habitacion :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Carnet de extrangeria", "Pasaporte" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        BotonRegistro.setBackground(new java.awt.Color(174, 190, 213));
        BotonRegistro.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BotonRegistro.setForeground(new java.awt.Color(51, 51, 51));
        BotonRegistro.setText("Register");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo Documento:");

        jLabel10.setText("Numero DNI:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(estancia))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(BotonSauna, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BotonAguaCaliente)
                                    .addGap(27, 27, 27)))
                            .addComponent(ingresoName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEstacionamiento))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingresoDNI)
                                    .addComponent(jComboBox1, 0, 168, Short.MAX_VALUE))
                                .addGap(276, 276, 276))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHabitacionInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingresoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresoName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnHabitaciones)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BotonSauna)
                                .addComponent(BotonAguaCaliente)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHabitacionInfo)
                            .addComponent(BotonEstacionamiento)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(estancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(BotonRegistro)
                .addGap(15, 15, 15))
        );

        wp.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 480, 390));

        BtnHabitaciones1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnHabitaciones1.setText("Cerrar sesion");
        BtnHabitaciones1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnHabitaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHabitaciones1ActionPerformed(evt);
            }
        });
        wp.add(BtnHabitaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 110, 40));

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        jLabel9.setText("Operador : David Rolando");
        wp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wp, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBoletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBoletasActionPerformed
        if (this.reservaActual != null && this.clienteActual != null) {
            BoletaDTO boleta = new BoletaDTO(clienteActual, reservaActual);
            try {
                BoletaService service = new BoletaService();
                int id = service.generarFactura(boleta);
                boleta.setFacturaID(id);
                GenerarBoleta.generarFactura(boleta);
                JOptionPane.showMessageDialog(this, "Factura generada con ID: " + id);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al generar factura: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe completar una reserva antes de generar una boleta.");
        }
    }//GEN-LAST:event_BotonBoletasActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed

        BookingForm ventanaTabla = new BookingForm();
        this.dispose();
        ventanaTabla.setVisible(true);
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        GoSolicitudForm ventanaStock = new GoSolicitudForm();
        ventanaStock.setLocationRelativeTo(null);
        ventanaStock.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnOperariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperariosActionPerformed
        RegistroEmpleados ventana = new RegistroEmpleados();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOperariosActionPerformed

    private void btnFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanzasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinanzasActionPerformed

    private void BtnHabitaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHabitaciones1ActionPerformed
        LoginForm ventana = new LoginForm();
        this.dispose();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_BtnHabitaciones1ActionPerformed

    private void btnLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiezaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BtnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHabitacionesActionPerformed
        HabitacionesForm ventanaHabitaciones = new HabitacionesForm(this);
        
        ventanaHabitaciones.setVisible(true);
        ventanaHabitaciones.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_BtnHabitacionesActionPerformed

    private void estanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estanciaActionPerformed

    }//GEN-LAST:event_estanciaActionPerformed

    private void BotonEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstacionamientoActionPerformed

    }//GEN-LAST:event_BotonEstacionamientoActionPerformed

    private void BotonAguaCalienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAguaCalienteActionPerformed

    }//GEN-LAST:event_BotonAguaCalienteActionPerformed

    private void BotonSaunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSaunaActionPerformed

    }//GEN-LAST:event_BotonSaunaActionPerformed

    private void ingresoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNameActionPerformed

    }//GEN-LAST:event_ingresoNameActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        String nombre = ingresoName.getText();
        String dni = ingresoDNI.getText();
        String telefono = ingresoTelefono.getText();
        String diasEstanciaStr = estancia.getText();
        int diasDeEstancia;

        if (nombre.isEmpty() || dni.isEmpty() || telefono.isEmpty() || diasEstanciaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        if (this.habitacionSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una habitación.");
            return;
        }

        try {
            diasDeEstancia = Integer.parseInt(diasEstanciaStr);
            if (diasDeEstancia <= 0) {
                JOptionPane.showMessageDialog(this, "Días debe ser positivo.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Días inválido.");
            return;
        }

        ClienteDTO cliente = new ClienteDTO(0, nombre, dni, telefono);

        try {
            ClienteDAO clienteDAO = new ClienteDAO();
            int clienteId = clienteDAO.insertar(cliente);
            cliente.setClienteID(clienteId);
            this.clienteActual = cliente;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar cliente: " + e.getMessage());
            return;
        }

        List<ServicioAdicional> serviciosSeleccionados = new ArrayList<>();
        if (BotonSauna.isSelected()) {
            serviciosSeleccionados.add(new ServicioSauna());
        }
        if (BotonEstacionamiento.isSelected()) {
            serviciosSeleccionados.add(new ServicioEstacionamiento());
        }
        if (BotonAguaCaliente.isSelected()) {
            serviciosSeleccionados.add(new ServicioAguaCaliente());
        }

        ReservaDTO reserva = new ReservaDTO(0, clienteActual, habitacionSeleccionada, diasDeEstancia, serviciosSeleccionados);

        try {
            ReservaService reservaService = new ReservaService();
            int reservaId = reservaService.registrarReserva(reserva);
            reserva.setReservaID(reservaId);
            this.reservaActual = reserva;
            JOptionPane.showMessageDialog(this, "Reserva creada con éxito para " + clienteActual.getNombre());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al crear reserva: " + e.getMessage());
        }
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void ingresoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoTelefonoActionPerformed

    }//GEN-LAST:event_ingresoTelefonoActionPerformed

    private void ingresoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoDNIActionPerformed

    }//GEN-LAST:event_ingresoDNIActionPerformed

    private void btnOperarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperarios1ActionPerformed
        ChartForm ventana = new ChartForm();
         ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOperarios1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroClienteForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonAguaCaliente;
    private javax.swing.JButton BotonBoletas;
    private javax.swing.JRadioButton BotonEstacionamiento;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JRadioButton BotonSauna;
    private javax.swing.JButton BtnHabitaciones;
    private javax.swing.JButton BtnHabitaciones1;
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnFinanzas;
    private javax.swing.JButton btnLimpieza;
    private javax.swing.JButton btnOperarios;
    private javax.swing.JButton btnOperarios1;
    private javax.swing.JButton btnStock;
    private javax.swing.JTextField estancia;
    private javax.swing.JTextField ingresoDNI;
    private javax.swing.JTextField ingresoName;
    private javax.swing.JTextField ingresoTelefono;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblHabitacionInfo;
    private javax.swing.JPanel wp;
    // End of variables declaration//GEN-END:variables
}
