package vista.forms;

import javax.swing.JOptionPane; 
import modelo.entidades.Empleado; 
import modelo.logica.*;
/**
 *
 * @author alexg
 */
public class RegistroEmpleados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroEmpleados.class.getName());

    private GestorHotel gestor;
    
    public RegistroEmpleados() {
        initComponents();
        gestor = new GestorHotel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idEmpleado = new javax.swing.JTextField();
        NombreEmpleado = new javax.swing.JTextField();
        DniEmpleado = new javax.swing.JTextField();
        TipoDni = new javax.swing.JComboBox<>();
        RolEmpleado = new javax.swing.JComboBox<>();
        ContraEmpleado = new javax.swing.JPasswordField();
        ConfirmContraEmpleado = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        TelefonoEmpleado = new javax.swing.JTextField();
        BtnRgtrEmpleado = new javax.swing.JButton();
        BtnAtrasEmpleado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        EmailEmpleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo del Empleado:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Nombre y Apellido:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel5.setText("Confirmar Contraseña:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel6.setText("DNI:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel7.setText("ROL:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        idEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(idEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 410, -1));
        jPanel2.add(NombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 410, -1));

        DniEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DniEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(DniEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 250, -1));

        TipoDni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Carnet de Extrangeria", "Visa de Trabajo" }));
        TipoDni.setToolTipText("");
        TipoDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDniActionPerformed(evt);
            }
        });
        jPanel2.add(TipoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 120, -1));

        RolEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado", "Limpieza" }));
        jPanel2.add(RolEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 120, -1));

        ContraEmpleado.setText("jPasswordField1");
        jPanel2.add(ContraEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 410, -1));

        ConfirmContraEmpleado.setText("jPasswordField2");
        jPanel2.add(ConfirmContraEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 410, -1));

        jLabel8.setText("Telefono:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));
        jPanel2.add(TelefonoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 410, -1));

        BtnRgtrEmpleado.setText("Registrar");
        BtnRgtrEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRgtrEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(BtnRgtrEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 131, 40));

        BtnAtrasEmpleado.setText("Atras");
        jPanel2.add(BtnAtrasEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 126, 40));

        jLabel9.setText("Email:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        EmailEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(EmailEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 410, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Nuevos Empleados");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 250, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDniActionPerformed

    private void idEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmpleadoActionPerformed

    private void DniEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DniEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DniEmpleadoActionPerformed

    private void EmailEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailEmpleadoActionPerformed

    private void BtnRgtrEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRgtrEmpleadoActionPerformed
        String nombreCompleto = NombreEmpleado.getText();
        String dni = DniEmpleado.getText();
        String telefono = TelefonoEmpleado.getText();
        String email = EmailEmpleado.getText();
        String tipoDocumento = (String) TipoDni.getSelectedItem();
        String nombreRol = (String) RolEmpleado.getSelectedItem(); // Rol en String
        String contrasena = new String(ContraEmpleado.getPassword());
        String confirmarContrasena = new String(ConfirmContraEmpleado.getPassword());
        if (nombreCompleto.isEmpty() || dni.isEmpty() || contrasena.isEmpty() || !contrasena.equals(confirmarContrasena)) {
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos y las contraseñas deben coincidir.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Crear entidad Empleado (que hereda de Persona)
        Empleado nuevoEmpleado = new Empleado(nombreCompleto, dni, telefono, email, tipoDocumento);

        // 3. Llamar al Gestor de Hotel
        if (gestor.registrarEmpleado(nuevoEmpleado, contrasena, nombreRol)) {
            JOptionPane.showMessageDialog(this, "Operario " + nombreCompleto + " registrado con éxito. Su usuario es su DNI.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            // Limpiar campos
            NombreEmpleado.setText("");
            DniEmpleado.setText("");
            TelefonoEmpleado.setText("");
            EmailEmpleado.setText("");
            ContraEmpleado.setText("");
            ConfirmContraEmpleado.setText("");
            RolEmpleado.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el operario. Verifique logs (DNI duplicado, rol inexistente, etc.).", "Error de Registro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnRgtrEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroEmpleados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtrasEmpleado;
    private javax.swing.JButton BtnRgtrEmpleado;
    private javax.swing.JPasswordField ConfirmContraEmpleado;
    private javax.swing.JPasswordField ContraEmpleado;
    private javax.swing.JTextField DniEmpleado;
    private javax.swing.JTextField EmailEmpleado;
    private javax.swing.JTextField NombreEmpleado;
    private javax.swing.JComboBox<String> RolEmpleado;
    private javax.swing.JTextField TelefonoEmpleado;
    private javax.swing.JComboBox<String> TipoDni;
    private javax.swing.JTextField idEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
