/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import logica.GestorHotel;
import modelo.Habitacion;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author extru
 */
public class CuartosDisponibles extends javax.swing.JFrame implements ActionListener {
    
      private GestorHotel gestorCentral;
    
    // 2. Mapa para asociar los botones con su número de Habitacion
    // Esto es necesario para usar el actionListener en todos los botones
    private Map<JButton, Integer> botonesHabitaciones; 
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CuartosDisponibles.class.getName());

    /**
     * Creates new form CuartosDisponibles
     */
    public CuartosDisponibles() {
        
         this.gestorCentral = new GestorHotel();
        this.botonesHabitaciones = new HashMap<>();
        
        initComponents();
    }
    
    private void configurarBotonesIniciales() {
    
    // Ejemplo de configuración para el botón HabitacionSimple1
    JButton b101 = HabitacionSimple1;
    b101.setActionCommand("101"); 
    b101.addActionListener(this);
    
    JButton b102 = HabitacionSimple2;
    b102.setActionCommand("102"); 
    b102.addActionListener(this);  
    
    JButton b201 = HabitacionDoble1;
    b201.setActionCommand("201"); 
    b201.addActionListener(this);  
    
    JButton b202 = HabitacionDoble2;
    b202.setActionCommand("202"); 
    b202.addActionListener(this);  
    
    JButton b301 = HabitacionTriple1;
    b301.setActionCommand("301"); 
    b301.addActionListener(this);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        HabitacionSimple1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        HabitacionSimple2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        HabitacionDoble1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        HabitacionDoble2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        HabitacionTriple1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Habitaciones Disponibles");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 20));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HabitacionSimple1.setBackground(new java.awt.Color(0, 102, 0));
        HabitacionSimple1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HabitacionSimple1.setText("Habitacion Simple - 101");
        HabitacionSimple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitacionSimple1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(HabitacionSimple1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HabitacionSimple1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 180, 70));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HabitacionSimple2.setBackground(new java.awt.Color(0, 102, 0));
        HabitacionSimple2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HabitacionSimple2.setText("Habitacion Simple - 102");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(HabitacionSimple2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HabitacionSimple2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 70));

        jPanel5.setBackground(new java.awt.Color(204, 102, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HabitacionDoble1.setBackground(new java.awt.Color(204, 102, 0));
        HabitacionDoble1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HabitacionDoble1.setText("Habitacion Doble - 201");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HabitacionDoble1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HabitacionDoble1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 70));

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HabitacionDoble2.setBackground(new java.awt.Color(204, 102, 0));
        HabitacionDoble2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HabitacionDoble2.setText("Habitacion Doble - 202");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HabitacionDoble2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HabitacionDoble2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 170, 70));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        HabitacionTriple1.setBackground(new java.awt.Color(0, 153, 153));
        HabitacionTriple1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HabitacionTriple1.setText("Habitacion Triple - 301");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HabitacionTriple1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HabitacionTriple1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HabitacionSimple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitacionSimple1ActionPerformed
        // TODO add your handling code here:
        
        
        
        
       
    }//GEN-LAST:event_HabitacionSimple1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CuartosDisponibles().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HabitacionDoble1;
    private javax.swing.JButton HabitacionDoble2;
    private javax.swing.JButton HabitacionSimple1;
    private javax.swing.JButton HabitacionSimple2;
    private javax.swing.JButton HabitacionTriple1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables

    @Override
    
    

    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

    }
   
    
    private void actualizarAspectoBoton(JButton boton, Habitacion h) {
    String nombreBase = "Habitacion-" + h.getNumero(); 
    String estadoTexto = h.getEstadoTexto(); 
    
    // NOTA: El diseñador ha puesto los botones dentro de JPanels de color.
    
    if (h.estaOcupada()) {
        boton.setBackground(Color.RED);
        boton.setForeground(Color.WHITE);
    } else {
        boton.setBackground(Color.GREEN);
        boton.setForeground(Color.BLACK);
    }
    
    // Mantiene el nombre base y añade el estado actualizado
    boton.setText(nombreBase + " (" + estadoTexto + ")");
    
    // Estas líneas son cruciales cuando usas diseñadores
    boton.setOpaque(true); 
    boton.setBorderPainted(false);
    
}
    
    
}
