package vista;

import modelo.Boleta;
import logica.GeneradorHtmlBoleta;
import modelo.Reserva;
import modelo.Cliente;
import logica.GestorHotel;
import modelo.Habitacion;
import javax.swing.JOptionPane;

public class CustomerRegistration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerRegistration.class.getName());
    
    //atributos nuevos
    private GestorHotel gestor;
    private Cliente clienteActual;
    private Reserva reservaActual;

    public CustomerRegistration() {
        initComponents();
        this.gestor = new GestorHotel();
        String[] tipos = gestor.getTiposDeHabitacionDisponibles();
        elegirTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(tipos));
        //aca se cargaran las habitaciones disponibles
    }
    public CustomerRegistration(GestorHotel gestor) {
        initComponents(); // Este método dibuja la ventana
        this.gestor = gestor; // Guardamos la referencia al gestor que nos pasaron
        
        // 1. Le pedimos al gestor la lista de tipos de habitación disponibles.
        String[] tipos = gestor.getTiposDeHabitacionDisponibles();
        elegirTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(tipos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonBoletas = new javax.swing.JButton();
        BotonReservas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresoDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ingresoTelefono = new javax.swing.JTextField();
        BotonRegistro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ingresoName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        elegirTipoHabitacion = new javax.swing.JComboBox<>();
        BotonSauna = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        BotonAguaCaliente = new javax.swing.JRadioButton();
        BotonEstacionamiento = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        estancia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wp.setBackground(new java.awt.Color(249, 250, 255));
        wp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(174, 190, 213));

        jPanel2.setBackground(new java.awt.Color(202, 218, 241));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        BotonBoletas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonBoletas.setForeground(new java.awt.Color(51, 51, 51));
        BotonBoletas.setText("Ticket");
        BotonBoletas.setBorder(null);
        BotonBoletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBoletasActionPerformed(evt);
            }
        });

        BotonReservas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonReservas.setForeground(new java.awt.Color(51, 51, 51));
        BotonReservas.setText("Booking");
        BotonReservas.setBorder(null);
        BotonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(574, 574, 574))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(BotonBoletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(BotonBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        wp.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 490));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Registro del Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        wp.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 220, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DNI");

        ingresoDNI.setBorder(null);
        ingresoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDNIActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Celular");

        ingresoTelefono.setBorder(null);
        ingresoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoTelefonoActionPerformed(evt);
            }
        });

        BotonRegistro.setBackground(new java.awt.Color(174, 190, 213));
        BotonRegistro.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BotonRegistro.setForeground(new java.awt.Color(51, 51, 51));
        BotonRegistro.setText("Register");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Extra");

        ingresoName.setBorder(null);
        ingresoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNameActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Room type");

        elegirTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Doble", "Triple" }));
        elegirTipoHabitacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        elegirTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirTipoHabitacionActionPerformed(evt);
            }
        });

        BotonSauna.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotonSauna.setText("  sauna");
        BotonSauna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSaunaActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nombre");

        BotonAguaCaliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotonAguaCaliente.setText("  Hot water");

        BotonEstacionamiento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotonEstacionamiento.setText("  Parking lot");

        jLabel4.setText("Dias de Estancia:");

        estancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estanciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(estancia, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonSauna, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(ingresoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(elegirTipoHabitacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(121, 121, 121))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(BotonAguaCaliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ingresoName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                                .addGap(58, 58, 58)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(BotonEstacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 101, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ingresoDNI)
                                    .addComponent(jSeparator1))
                                .addGap(41, 41, 41))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresoName, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(ingresoDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elegirTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSauna)
                    .addComponent(BotonAguaCaliente)
                    .addComponent(BotonEstacionamiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(estancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        wp.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 470, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoDNIActionPerformed

    private void ingresoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoTelefonoActionPerformed

    private void ingresoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNameActionPerformed

    private void BotonSaunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSaunaActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_BotonSaunaActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        //Recoleccion de datos
        String nombre = ingresoName.getText();
        String dni = ingresoDNI.getText();
        String telefono = ingresoTelefono.getText();
        String diasEstanciaStr = estancia.getText();
        
        String tipoHabitacionSeleccionada = (String) elegirTipoHabitacion.getSelectedItem();
        
        boolean extraSauna = BotonSauna.isSelected();
        boolean extraAguaCaliente = BotonAguaCaliente.isSelected();
        boolean extraEstacionamiento = BotonEstacionamiento.isSelected();
        
        //Validacion entradas
        if (nombre.isEmpty() || dni.isEmpty() || diasEstanciaStr.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int diasDeEstancia;
        try {
            // Intentamos convertir el texto de los días a un número entero
            diasDeEstancia = Integer.parseInt(diasEstanciaStr);
            if (diasDeEstancia <= 0) {
                JOptionPane.showMessageDialog(this, "El número de días debe ser mayor a cero.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            // Si el usuario escribió letras en vez de números, mostramos un error
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para los días de estancia.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.clienteActual = gestor.registrarNuevoCliente(nombre, dni,telefono);
        
        Habitacion habitacionSeleccionada = gestor.buscarHabitacionPorTipo(tipoHabitacionSeleccionada);

        if (habitacionSeleccionada != null) {
            this.reservaActual = gestor.crearNuevaReserva(
                clienteActual,
                habitacionSeleccionada,
                diasDeEstancia,
                extraSauna,
                extraAguaCaliente,
                extraEstacionamiento
            );
            // --- 4. VISTA: MOSTRAR RESULTADO ---
            JOptionPane.showMessageDialog(this, "Reserva creada con éxito para " + clienteActual.getNombre() + " en la habitación " + habitacionSeleccionada.getNumero());
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear la reserva. No hay habitaciones de ese tipo disponibles.", "Sin Disponibilidad", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void elegirTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirTipoHabitacionActionPerformed
        //ypur code here
    }//GEN-LAST:event_elegirTipoHabitacionActionPerformed

    private void BotonBoletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBoletasActionPerformed
        if (this.reservaActual != null && this.clienteActual != null) {
            // Asegúrate de que Boleta esté en el paquete 'modelo'
            Boleta nuevaBoleta = new Boleta(this.clienteActual, this.reservaActual);
            GeneradorHtmlBoleta.generarFactura(nuevaBoleta);
        } else {
            JOptionPane.showMessageDialog(this, "Debe registrar una reserva antes de generar una boleta.", "Acción Requerida", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BotonBoletasActionPerformed

    private void estanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estanciaActionPerformed

    private void BotonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReservasActionPerformed
        // TODO add your handling code here:
        
        TablaRegistro ventanaTabla = new TablaRegistro(this.gestor);

        ventanaTabla.setVisible(true);
        
    }//GEN-LAST:event_BotonReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
  public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(() -> new CustomerRegistration().setVisible(true)); 
  }
        /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>     
//
//        /* Create and display the form */
//         java.awt.EventQueue.invokeLater(() -> new CustomerRegistration().setVisible(true)); 
//    }
// 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonAguaCaliente;
    private javax.swing.JButton BotonBoletas;
    private javax.swing.JRadioButton BotonEstacionamiento;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JButton BotonReservas;
    private javax.swing.JRadioButton BotonSauna;
    private javax.swing.JComboBox<String> elegirTipoHabitacion;
    private javax.swing.JTextField estancia;
    private javax.swing.JTextField ingresoDNI;
    private javax.swing.JTextField ingresoName;
    private javax.swing.JTextField ingresoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel wp;
    // End of variables declaration//GEN-END:variables
}