

package vista;

import logica.Login;

public class LoginUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginUsuario.class.getName());

    public LoginUsuario() {
        
        this.getRootPane().setDefaultButton(BotonLogin);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextoTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SeparadorContraseña = new javax.swing.JSeparator();
        TextoContraseña = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JTextField();
        SeparadorUsuario = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        BotonLogin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BotonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(215, 225, 234));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        TextoTitulo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        TextoTitulo.setForeground(new java.awt.Color(51, 51, 51));
        TextoTitulo.setText("Welcome!");
        jPanel1.add(TextoTitulo);
        TextoTitulo.setBounds(100, 40, 104, 28);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 170, 90, 18);

        SeparadorContraseña.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(SeparadorContraseña);
        SeparadorContraseña.setBounds(30, 220, 247, 10);

        TextoContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextoContraseña.setBorder(null);
        TextoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(TextoContraseña);
        TextoContraseña.setBounds(30, 190, 250, 24);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 90, 18);

        TextoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextoUsuario.setBorder(null);
        TextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(TextoUsuario);
        TextoUsuario.setBounds(30, 120, 250, 24);

        SeparadorUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(SeparadorUsuario);
        SeparadorUsuario.setBounds(30, 150, 247, 10);

        jPanel2.setBackground(new java.awt.Color(215, 225, 234));

        BotonLogin.setBackground(new java.awt.Color(215, 225, 234));
        BotonLogin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonLogin.setText("Login");
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(170, 270, 110, 40);

        jPanel3.setBackground(new java.awt.Color(215, 225, 234));

        BotonExit.setBackground(new java.awt.Color(215, 225, 234));
        BotonExit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonExit.setText("Exit");
        BotonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 270, 100, 40);

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 310, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoContraseñaActionPerformed

    private void TextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoUsuarioActionPerformed

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed
        // TODO add your handling code here:
        
        Login login = new Login(TextoUsuario.getText(), TextoContraseña.getText());
        login.loginUser();
       
         this.setVisible(false);
       
       
        
        
    }//GEN-LAST:event_BotonLoginActionPerformed

    private void BotonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(() -> new LoginUsuario().setVisible(true)); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonExit;
    private javax.swing.JButton BotonLogin;
    private javax.swing.JSeparator SeparadorContraseña;
    private javax.swing.JSeparator SeparadorUsuario;
    private javax.swing.JTextField TextoContraseña;
    private javax.swing.JLabel TextoTitulo;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
